### ISSUE TITLE
Azure works

### ISSUE THREAD

**Issue by ljani** [drizzt/vps2arch#10]
I used Ubuntu 14.04 LTS and everything went fine.

Many thanks, this was an awesome script!

Two suggestions:
- Add root check. Otherwise we will fail with a not so clear error message:

```
jani@sauna:~$ ./vps2arch
./vps2arch: 43: ./vps2arch: cannot create sha1sums.txt: Permission denied
--2016-02-04 18:42:56--  http://mirror.rackspace.com/archlinux/iso/latest/sha1sums.txt
Resolving mirror.rackspace.com (mirror.rackspace.com)... 94.236.26.35
Connecting to mirror.rackspace.com (mirror.rackspace.com)|94.236.26.35|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 244 [text/plain]
Saving to: ‘STDOUT’

 0% [                                                                                                                                           ] 0           --.-K/s   in 0s


Cannot write to ‘-’ (Broken pipe).
jani@sauna:~$
```

As you can see, I forgot to use `sudo` and thus noticed the following problem:
- [`dgix.ru`](https://github.com/drizzt/vps2arch/blob/f6e56798fd1eada749d811ae5263a86dbc8d52b2/vps2arch#L316) seems to be [dead](http://dgix.ru), remove it

**Comment by z3ntu** [comment]
Worked for me too! Thanks!!

**Comment by mtrimarchi** [comment]
Worked for me, Azure with an Ubuntu 14.04 LTS (clean deploy).

Many thanks @drizzt !!!

**Comment by PoisonousJohn** [comment]
Hi everybody! AFAIK to fully support linux distro in Azure, there should be https://github.com/Azure/WALinuxAgent installed. Do I need install it after converting VM to Arch?
