### ISSUE TITLE
Nasty bug with /etc/systemd/network/default.network

### ISSUE THREAD

**Issue by Keziolio** [drizzt/vps2arch#16]
I used your useful script on a cloudatcost ubuntu 14 vps, it all went perfectly but internet connection was not working.

After some head banging i figured out the source of the problem: http://imgur.com/LbKtP7i
obviously there's a problem with the gateway line

Now everything works but I wanted to report anyway.

**Comment by drizzt** [comment]
It should be closed, thank you
