### ISSUE TITLE
Cloudatcost Debian 8 doesn't work

### ISSUE THREAD

**Issue by muflone** [drizzt/vps2arch#17]
Using cloudatcost DevPro cloud 3 with Debian 8 the script runs fine but after the reboot it's unable to mount root partition.

The first symptom is a wrong UUID for the root partition but the real issue is that cannot find the LVM member. All the tools to manage and mount the LVMs seems to lack.

**Comment by muflone** [comment]
![schermata da 2016-06-26 22-40-16](https://cloud.githubusercontent.com/assets/1284163/16364763/41a0f2d6-3bef-11e6-8b25-2ae2298cb78e.png)

**Comment by drizzt** [comment]
can you try to use one of the [supported distros](https://github.com/drizzt/vps2arch/wiki/Tested-VPS-Providers) such as CentOS 6, CentOS 7 or Ubuntu 14.04?

**Comment by muflone** [comment]
Both Ubuntu 14.04 and CentOS 7 worked fine.

**Comment by drizzt** [comment]
Added to wiki
