### ISSUE TITLE
CloudAtCost CentOS7

### ISSUE THREAD

**Issue by shauder** [drizzt/vps2arch#2]
I get an error on line 
 > 99 | "/root.$cpu_type/usr/lib/ld-linux.so."* --library-path "/root.$cpu_type/usr/lib" \

Can't find whats needed.

**Comment by drizzt** [comment]
Hi,
can you please paste a complete log or at least more informations about the error?

**Comment by shauder** [comment]
Really all it says is it cant find that and then ends. I'll try and get a
paste when I'm home.

**Comment by drizzt** [comment]
Fixed in a01af5d8acee1200ab6fa497213917c8b489529b
