### ISSUE TITLE
Amazon AWS EC2

### ISSUE THREAD

**Issue by grazzolini** [drizzt/vps2arch#21]
Reporting that I successfully converted some ubuntu HVM machines running on EC2 to arch using this script. I tried using their custom AMI system for a while, but it was much easier to deploy an ubuntu server first and convert it later to arch using vps2arch. I didn't test their other linux offerings, such as Amazon Linux, Red Hat or Suse, but I don't see why they wouldn't work also.

**Comment by drizzt** [comment]
Hi,
can you please give me the ami id of you ubuntu machine so I can update the wiki page?

**Comment by grazzolini** [comment]
Sure, the one I used was ami-dc48dcb0.
