### ISSUE TITLE
CentOS 6 and 7 do not work anymore with CloudAtCost .

### ISSUE THREAD

**Issue by ZeBaal** [drizzt/vps2arch#27]
I just tried the script with CentOS 6 and 7 at CloudAtCost and both failed when comes the time to install grub with the following error on the last line:

Generating grub configuration file ...
Found linux image: /boot/vmlinuz-linux
Found initrd image(s) in /boot: initramfs-linux.img
Found fallback initrd image(s) in /boot: initramfs-linux-fallback.img
done
Installing for i386-pc platform.
grub-install: error: unable to identify a filesystem in hostdisk//dev/sda; safety check can't be performed.

EDIT: The same problem is also happening with Ubuntu 14.04.1…

**Comment by SR-G** [comment]
Exactly the same problem for me.

**Comment by drizzt** [comment]
Since Cloud At Cost doesn't want to create me another server:

	We are sorry but your server is waiting to be built.
	This is caused by overwhelming popularity to our Developer CloudPRO service.
	I am sorry but there is nothing you can do but wait.
	PLEASE DO NOT OPEN A TICKET!

Can you try to launch `./vps2arch -b syslinux` instead of plain `./vps2arch`?

**Comment by SR-G** [comment]
I tryed with `vps2arch -b syslinux`, sadly it still doesn't work.
Please find attached the whole execution log.

I launched the script on a CloundAtCost VPS installed with CentOS-7-64bit
[vps2arch-cloudatcost.txt](https://github.com/drizzt/vps2arch/files/794438/vps2arch-cloudatcost.txt)

**Comment by drizzt** [comment]
It should work now, thank you

**Comment by SR-G** [comment]
Ok i can also confirm that it's working now from CloudAtCost / CentOS 6.7 64bit (thanks for the correction), despite a few errors in the log : 

```
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-fallback.img
==> Image generation successful
(2/7) Updating udev hardware database...
(3/7) Updating system user accounts...
(4/7) Creating temporary files...
error: command failed to execute correctly
(5/7) Arming ConditionNeedsUpdate...
```

```
[root@localhost ~]# sync ; reboot -f
Failed to read reboot parameter file: No such file or directory
Rebooting.
```
