### ISSUE TITLE
error: krb5: signature from "Levente Polyak (anthraxx) levente@leventepolyak.net" is unknown trust

### ISSUE THREAD

**Issue by forbi** [drizzt/vps2arch#30]
`(134/134) checking package integrity                                     [########################################] 100%
error: krb5: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust
:: File /mnt/var/cache/pacman/pkg/krb5-1.13.7-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: libpsl: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust
:: File /mnt/var/cache/pacman/pkg/libpsl-0.17.0-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.
==> ERROR: Failed to install packages to new root
`

**Comment by KarlFiabeschi** [comment]
me too, but i cant apt-get install ca-certificates because no apt system anymore.
i have only

boot/        dev/         etc/         proc/        root.x86_64/ run/         sys/         tmp/         var/

**Comment by forbi** [comment]
@KarlFiabeschi You will need to re install the server and wait for a fix. the ca-certificates from debian won't solve the problem in Arch. I guess that the keyring is outdated.

**Comment by KarlFiabeschi** [comment]
Yep, i tried yesterday 2 times. 

last update is on 04-01-2017:
https://www.archlinux.org/packages/core/any/archlinux-keyring/

**Comment by forbi** [comment]
@KarlFiabeschi Todays is working, arch updated some stuff :+1:
