### ISSUE TITLE
Add Vultr to the list of compatible VPS providers

### ISSUE THREAD

**Issue by chmercesmoreira** [drizzt/vps2arch#32]
I just tested vps2arch following the basic steps and everything is working flawlessly.
VPS provider: Vultr
Distribution before the change: Ubuntu 16.04 64 bits

**Comment by adamantium169** [comment]
16.04 works, but 17 didn't work on Vultr.

I ended up finding the custom ISO feature in Vultr anyway, you can upload any ISO you want :)

**Comment by chmercesmoreira** [comment]
I specified explicitly that I have used Ubuntu version 16.04 when I tested vps2arch.

**Comment by adamantium169** [comment]
Yeah, I can read. I wanted to point out that you don't even need to use this with Vultr. Not only do they have Arch ISO as an option (it's in their ISO Library), but as I mentioned you can upload any ISO you want to boot from.

I mean, even the readme has "It should be only used if your VPS provider doesn't provide you an Arch Linux image".

**Comment by chmercesmoreira** [comment]
I tried using the arch ISO from the ISO Library before but the procedure to get everything working remotely is not so easy for me, so I end up using vps2arch.
