### ISSUE TITLE
Scalaway is unsupported

### ISSUE THREAD

**Issue by louwers** [drizzt/vps2arch#35]
![screenshot_2017-07-06_11-01-16](https://user-images.githubusercontent.com/649392/27903690-7758ba90-623a-11e7-8d59-2eecf9217d3e.png)

Tried Ubuntu 14.04, 16.04 and Gentoo. All have the same result on [Scaleway](https://www.scaleway.com/)

**Comment by drizzt** [comment]
Scaleway is supported and actually I have an instance on Scaleway.

Did you read the wiki page https://github.com/drizzt/vps2arch/wiki/How-to-use-on-Scaleway?

**Comment by louwers** [comment]
Oh I missed that...

Thanks.
