### ISSUE TITLE
Exclude http://mirrors.evowise.com/archlinux/ mirror

### ISSUE THREAD

**Issue by muflone** [drizzt/vps2arch#42]
The mirror http://mirrors.evowise.com/archlinux/ contains outdated ISOs, that cannot be used for Arch Linux installation.
If the first global mirror fails, then evowise will be the second mirror to be used, resulting in a non usable system for many **Kernel too old** errors during the installation from the outdated ISO.

A more elegant solution would download https://www.archlinux.org/mirrors/status/json/ to get the mirrors list that allow to download recent ISO to install the OS from.
If you're interested I could submit a PR.

**Comment by bleedingpixels** [comment]
Submit the PR please.  Even it doesn't get pulled, I would like a solution.

**Comment by zasdza** [comment]
I just added  `127.0.0.1 mirrors.evowise.com` to avoid this.
The 3rd one in global list is Okay.
Wait for the PR.

**Comment by muflone** [comment]
The bug was fixed https://bugs.archlinux.org/task/55654 on the mirror
