### ISSUE TITLE
Vscale.io Debian 8 works!

### ISSUE THREAD

**Issue by murmuringvoices** [drizzt/vps2arch#6]
Just want to let you know that [https://vscale.io](https://vscale.io/?refcode=yuxe9f4j5r) supports this script with Debian 8

Thank you very much for such great work!

If you are interested in trying Vscale - you can use [my reflink](https://vscale.io/?refcode=yuxe9f4j5r) , you will get 2 months 512mb/1core or 1 month 1024mb/1core

**Comment by drizzt** [comment]
Added to wiki
